dset_type: npy
gen_type: muse
seed: 1234
z_shape: [8, 16, 16]
autoencoder:
  config_file: 'vq-f16-jax.yaml'
train:
  n_steps: 99999999
  batch_size: 2048
  log_interval: 50
  eval_interval: 5000
  save_interval: 5000
  fid_interval: 50000
eval:
  n_samples: 10000
  sample_steps: 12
optimizer:
  name: 'adamw'
  lr: 0.0004
  weight_decay: 0.03
  betas: [0.99, 0.99]
lr_scheduler:
  name: 'customized'
  warmup_steps: 5000
nnet:
  name: 'uvit_t2i_vq'
  img_size: 16
  codebook_size: 1024
  embed_dim: 768
  depth: 24
  num_heads: 8
  mlp_ratio: 4
  qkv_bias: False
  num_classes: 1001
  use_checkpoint: False
  skip: True
muse:
  ignore_ind: -1
  smoothing: 0.1
  gen_temp: 4.5
dataset:
  name: 'imagenet256_features'
  path: 'assets/imagenet_vq_features'
  cfg: True
  p_uncond: 0.15
sample:
  sample_steps: 12
  n_samples: 50000
  mini_batch_size: 50
  cfg: True
  linear_inc_scale: True
  scale: 3.0
  path: ''
